apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-single-cluster-v2
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error

  generators:
    - git:
        repoURL: https://github.com/guyyakobov/my-proj.git
        revision: main
        files:
          - path: helm/charts/*/values-*.yaml
        values:
          system: my-proj
  template:
    metadata:
      name: '{{ .path.basename }}-{{ trimSuffix ".yaml" (trimPrefix "values-" .path.filename) }}'
      labels:
        environment: '{{ trimSuffix ".yaml" (trimPrefix "values-" .path.filename) }}'
        service: '{{ .path.basename }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/guyyakobov/my-proj.git
        targetRevision: main
        path: '{{ .path.path }}'
        helm:
          # ignoreMissingValueFiles: true
          valueFiles:
            - ../../global-values/values.yaml
            - '../../global-values/{{ .path.filename }}'
            - values.yaml
            - '{{ .path.filename }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .values.system }}-{{ trimSuffix ".yaml" (trimPrefix "values-" .path.filename) }}'
      ignoreDifferences:
        - group: apps
          kind: Deployment
          jsonPointers:
            - /spec/replicas
        - group: apps
          kind: StatefulSet
          jsonPointers:
            - /spec/replicas   
      syncPolicy:
        syncOptions:
          - RespectIgnoreDifferences=true
  templatePatch: |
    {{- $env := trimSuffix ".yaml" (trimPrefix "values-" .path.filename) }}
    {{- if eq $env "dev" }}
    spec:
      syncPolicy:
        automated:
          enabled: true
          prune: true
          selfHeal: false
        syncOptions:
          - RespectIgnoreDifferences=true
    {{- end }}
  syncPolicy:
    applicationsSync: create-update
    preserveResourcesOnDeletion: true