apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-prod-multi-region
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/guyyakobov/my-proj.git
              revision: main
              files:
                - path: helm/charts/*/values-prod.yaml
              values:
                system: my-proj
          - clusters:
              selector:
                matchLabels:
                  environment: prod
                matchExpressions:
                  - key: region
                    operator: Exists
  template:
    metadata:
      name: '{{ .path.basename }}-prod-{{ index .metadata.labels "region" }}'
      labels:
        environment: prod
        service: '{{ .path.basename }}'
        region: '{{ index .metadata.labels "region" }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/guyyakobov/my-proj.git
        targetRevision: main
        path: '{{ .path.path }}'
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - ../../common-values/values.yaml
            - '../../common-values/{{ .path.filename }}'
            - '../../common-values/values-{{ index .metadata.labels "environment" }}-{{ index .metadata.labels "region" }}.yaml'
            - values.yaml
            - '{{ .path.filename }}'
            - 'values-{{ index .metadata.labels "environment" }}-{{ index .metadata.labels "region" }}.yaml'
      destination:
        server: '{{ .server }}'
        namespace: '{{ .values.system }}-{{ index .metadata.labels "environment" }}'
      ignoreDifferences:
        - group: apps
          kind: Deployment
          jsonPointers:
            - /spec/replicas
        - group: apps
          kind: StatefulSet
          jsonPointers:
            - /spec/replicas   
      syncPolicy:
        syncOptions:
          - RespectIgnoreDifferences=true
          - CreateNamespace=true
  syncPolicy:
    applicationsSync: create-update
    preserveResourcesOnDeletion: true
