on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  sync:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      ARGOCD_SERVER: ${{ vars.ARGOCD_SERVER }}
      ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_AUTH_TOKEN }}
      ARGOCD_OPTS: --grpc-web
    steps:
      - name: Install Argo CD CLI
        run: |
          sudo curl -fsSLo /usr/local/bin/argocd \
            "https://github.com/argoproj/argo-cd/releases/download/${{vars.ARGOCD_VERSION}}/argocd-linux-amd64"
          sudo chmod +x /usr/local/bin/argocd
          argocd version --client
          
      - name: Sync application
        run: |
          set -euo pipefail
          SELECTOR='service=${{ inputs.service }},env=${{ inputs.environment }}'

          echo "Syncing applications with the following labels: service=${{ inputs.service }} and env=${{ inputs.environment }}"
          argocd app sync \
            -l "$SELECTOR" \
            --async
          
          echo "Waiting for applications to be healthy and synced..."
          argocd app wait \
            -l "$SELECTOR" \
            --sync \
            --health \
            --timeout 600